# [Model 2]
Random Forest
```{r}
library(party)
library(randomForest)
```
```{r}
train$Gender = as.factor(train$Gender)
train$Customer.Type  = as.factor(train$Customer.Type  )
train$Type.of.Travel = as.factor(train$Type.of.Travel)
train$Class = as.factor(train$Class)
test$Gender = as.factor(test$Gender)
test$Customer.Type  = as.factor(test$Customer.Type  )
test$Type.of.Travel = as.factor(test$Type.of.Travel)
test$Class = as.factor(test$Class)

```

```{r}
mod_rf=randomForest(satisfaction ~ Gender + Customer.Type + Age + Type.of.Travel + 
    Class + Flight.Distance + Inflight.wifi.service + Departure.Arrival.time.convenient + 
    Ease.of.Online.booking + Gate.location + Food.and.drink + 
    Online.boarding + Seat.comfort + Inflight.entertainment + 
    On.board.service + Leg.room.service + Baggage.handling + 
    Checkin.service + Inflight.service + Cleanliness + Departure.Delay.in.Minutes + 
    Arrival.Delay.in.Minutes, data=train, controls=cforest_control(mtry=2, mincriterion=0))
```

```{r}
pred=predict(mod_rf,test,type='class')
table(pred,test$satisfaction)
mean(pred==test$satisfaction)
```


